select
    claim_id,
    dealer_id,
    vin,
    fleet_id,
    technician_id,
    cast(filed_date as date) as filed_date,
    cast(repair_date as date) as repair_date,
    cast(claim_year as integer) as claim_year,
    cast(claim_month as integer) as claim_month,
    upper(claim_quarter) as claim_quarter,
    cast(mileage_at_repair as integer) as mileage_at_repair,
    trim(vehicle_model) as vehicle_model,
    cast(model_year as integer) as model_year,
    trim(claim_type) as claim_type,
    trim(symptom_reported) as symptom_reported,
    cast(total_parts_cost as numeric) as total_parts_cost,
    cast(total_labor_hours as numeric) as total_labor_hours,
    cast(total_labor_cost as numeric) as total_labor_cost,
    cast(total_claim_amount as numeric) as total_claim_amount,
    cast(num_line_items as integer) as num_line_items,
    trim(technician_narrative) as technician_narrative,
    trim(status) as status,
    cast(risk_score as integer) as risk_score,
    case when is_anomaly = 'Y' then true else false end as is_anomaly,
    nullif(trim(anomaly_tier), '') as anomaly_tier,
    nullif(trim(anomaly_flags), '') as anomaly_flags,
    cast(days_to_warranty_end as integer) as days_to_warranty_end,
    cast(prior_claims_on_vin as integer) as prior_claims_on_vin,
    nullif(trim(campaign_id), '') as campaign_id,
    case when pre_authorized = 'Y' then true else false end as pre_authorized,
    trim(submission_channel) as submission_channel

from {{ ref('fact_claims') }}
