name: 'reg'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  reg:
    +schema: raw

models:
  reg:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["Bronze"]
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ["Silver"]
    marts:
      +materialized: table
      +schema: marts
      +tags: ["Gold"]
